export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";

export const MARK_AS_FAVORITE_SUCCESS = "MARK_AS_FAVORITE_SUCCESS";
export const MARK_AS_DONE_SUCCESS = "MARK_AS_DONE_SUCCESS";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";